spring:
    cloud:
        config:
            overrideSystemProperties: false
eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
