spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/product
        username: web
        password: webuser
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect  # Parandatud Dialect klassi nimi
    flyway:
        baseline-on-migrate: true
        enabled: true
        baseline-description: "init"
        baseline-version: 0
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}


server:
    port: 8050